import { defineField, defineType } from 'sanity'
import { UsersIcon } from '@sanity/icons'

export const jobCategory = defineType({
  name: 'jobCategory',
  title: 'Job Category',
  type: 'document',
  icon: UsersIcon,
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'dimensions', title: 'Dimensions' },
    { name: 'inAction', title: 'In Action' },
    { name: 'stats', title: 'Stats' },
    { name: 'roster', title: 'Role Roster' },
    { name: 'bespoke', title: 'Bespoke CTA' },
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Category Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'name' },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'keyDimensionsAssessed',
      title: 'Key Dimensions Assessed',
      type: 'string',
      description: 'Comma-separated, e.g. "Customer excellence, stability, trust, structure"',
    }),
    defineField({
      name: 'heroHeadline',
      title: 'Hero Headline',
      type: 'string',
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroIntroCopy',
      title: 'Hero Intro Copy',
      type: 'text',
      rows: 3,
      group: 'hero',
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'dimensionsSectionHeading',
      title: 'Dimensions Section Heading',
      type: 'string',
      group: 'dimensions',
    }),
    defineField({
      name: 'dimensionsSectionBody',
      title: 'Dimensions Section Body',
      type: 'text',
      rows: 4,
      group: 'dimensions',
    }),
    defineField({
      name: 'dimensionsSectionImage',
      title: 'Dimensions Section Image',
      type: 'image',
      options: { hotspot: true },
      group: 'dimensions',
    }),
    defineField({
      name: 'inActionSectionHeading',
      title: 'In Action Section Heading',
      type: 'string',
      group: 'inAction',
    }),
    defineField({
      name: 'inActionSectionSubheading',
      title: 'In Action Section Subheading',
      type: 'text',
      rows: 2,
      group: 'inAction',
    }),
    defineField({
      name: 'inActionSectionImage',
      title: 'In Action Section Image',
      type: 'image',
      options: { hotspot: true },
      group: 'inAction',
    }),
    defineField({
      name: 'assessmentsBlockHeading',
      title: 'Assessments Block Heading',
      type: 'string',
      group: 'inAction',
    }),
    defineField({
      name: 'assessmentsBlockBody',
      title: 'Assessments Block Body',
      type: 'text',
      rows: 3,
      group: 'inAction',
    }),
    defineField({
      name: 'portalBlockHeading',
      title: 'Portal Block Heading',
      type: 'string',
      group: 'inAction',
    }),
    defineField({
      name: 'portalBlockBody',
      title: 'Portal Block Body',
      type: 'text',
      rows: 3,
      group: 'inAction',
    }),
    defineField({
      name: 'interviewBlockHeading',
      title: 'Interview Block Heading',
      type: 'string',
      group: 'inAction',
    }),
    defineField({
      name: 'interviewBlockBody',
      title: 'Interview Block Body',
      type: 'text',
      rows: 3,
      group: 'inAction',
    }),
    defineField({
      name: 'stat1Heading',
      title: 'Stat 1 Heading',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'stat1Body',
      title: 'Stat 1 Body',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'stat2Heading',
      title: 'Stat 2 Heading',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'stat2Body',
      title: 'Stat 2 Body',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'stat3Heading',
      title: 'Stat 3 Heading',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'stat3Body',
      title: 'Stat 3 Body',
      type: 'string',
      group: 'stats',
    }),
    defineField({
      name: 'roleRosterHeading',
      title: 'Role Roster Heading',
      type: 'string',
      group: 'roster',
    }),
    defineField({
      name: 'roleRosterSubheading',
      title: 'Role Roster Subheading',
      type: 'string',
      group: 'roster',
    }),
    defineField({
      name: 'bespokeSectionHeading',
      title: 'Bespoke Section Heading',
      type: 'string',
      group: 'bespoke',
    }),
    defineField({
      name: 'bespokeSectionBody',
      title: 'Bespoke Section Body',
      type: 'text',
      rows: 3,
      group: 'bespoke',
    }),
    defineField({
      name: 'bespokeCTALabel',
      title: 'Bespoke CTA Label',
      type: 'string',
      group: 'bespoke',
    }),
    defineField({
      name: 'bespokeSectionImage',
      title: 'Bespoke Section Image',
      type: 'image',
      options: { hotspot: true },
      group: 'bespoke',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'keyDimensionsAssessed',
      media: 'heroImage',
    },
    prepare({ title, subtitle, media }) {
      return {
        title,
        subtitle: subtitle || 'No dimensions set',
        media,
      }
    },
  },
})
