import type { MetadataRoute } from 'next';

/**
 * /robots.txt — generated by Next.js at build time.
 *
 * Public marketing pages are open to crawlers; internal/operational
 * routes are blocked. The guide page also returns a noindex tag in
 * its <head> for defence in depth.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',         // server endpoints
          '/admin/',       // Sanity Studio + internal client guide
          '/get-started/', // checkout flow — no need to crawl
        ],
      },
    ],
  };
}
