import { createClient } from '@sanity/client'
import * as dotenv from 'dotenv'
import * as path from 'path'

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  token: process.env.SANITY_API_TOKEN,
  apiVersion: '2024-01-01',
  useCdn: false,
})

const pricingTiers = [
  {
    _id: 'pricingTier-starter',
    _type: 'pricingTier',
    name: 'Starter',
    slug: { _type: 'slug', current: 'starter' },
    order: 1,
    isFeatured: false,
    tierLabel: 'Single edition',
    tagline: 'A one-off package of assessments to trial how Vero Assess works for a single role.',
    priceDisplay: '£3,500',
    annualPrice: 3500,
    paymentOptions: 'Pay in full',
    duration: 'Available to use for 12 months or until you have used your candidate credits',
    candidateLimit: 250,
    roleLimit: 1,
    ctaLabel: 'Find out more and buy',
    ctaType: 'buy',
    upgradeNote: "Upgrade from our Starter package and we'll take the £3,500 cost off your first subscription.",
  },
  {
    _id: 'pricingTier-essential',
    _type: 'pricingTier',
    name: 'Essential',
    slug: { _type: 'slug', current: 'essential' },
    order: 2,
    isFeatured: false,
    tierLabel: 'Annual subscription',
    tagline: 'Higher volumes and lower per candidate costs.',
    priceDisplay: '£9,000',
    annualPrice: 9000,
    paymentOptions: 'Pay monthly or annually',
    duration: 'Annual',
    candidateLimit: 1000,
    roleLimit: 5,
    ctaLabel: 'Find out more and buy',
    ctaType: 'buy',
  },
  {
    _id: 'pricingTier-growth',
    _type: 'pricingTier',
    name: 'Growth',
    slug: { _type: 'slug', current: 'growth' },
    order: 3,
    isFeatured: true,
    tierLabel: 'Annual subscription',
    tagline: 'Scale your hiring across multiple roles and higher volumes.',
    priceDisplay: '£18,000',
    annualPrice: 18000,
    paymentOptions: 'Pay monthly or annually',
    duration: 'Annual',
    candidateLimit: 2500,
    roleLimit: 20,
    ctaLabel: 'Find out more and buy',
    ctaType: 'buy',
  },
  {
    _id: 'pricingTier-scale',
    _type: 'pricingTier',
    name: 'Scale',
    slug: { _type: 'slug', current: 'scale' },
    order: 4,
    isFeatured: false,
    tierLabel: 'Annual subscription',
    tagline: 'Full platform access for high-volume, multi-role hiring.',
    priceDisplay: '£30,000',
    annualPrice: 30000,
    paymentOptions: 'Pay monthly or annually',
    duration: 'Annual',
    candidateLimit: 6000,
    roleLimit: 50,
    ctaLabel: 'Find out more and buy',
    ctaType: 'buy',
  },
  {
    _id: 'pricingTier-bespoke',
    _type: 'pricingTier',
    name: 'Bespoke',
    slug: { _type: 'slug', current: 'bespoke' },
    order: 5,
    isFeatured: false,
    tierLabel: 'Bespoke',
    tagline: 'Need a more customised solution?',
    ctaLabel: 'Talk to us',
    ctaType: 'contact',
    bespokeDescription: 'We also offer tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
  },
]

const jobCategories = [
  {
    _id: 'jobCategory-administration',
    _type: 'jobCategory',
    name: 'Administration',
    slug: { _type: 'slug', current: 'administration' },
    keyDimensionsAssessed: 'Customer excellence, stability, trust, structure',
    heroHeadline: 'Administration',
    heroIntroCopy: "Assess high volumes of candidates for administrative roles and identify the dependable talent that's right for your organisation.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in an administrative role, such as multi-tasking, judgement under pressure and emotional intelligence.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including customer excellence, stability, trust and structure, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-operations-and-logistics',
    _type: 'jobCategory',
    name: 'Operations and Logistics',
    slug: { _type: 'slug', current: 'operations-and-logistics' },
    keyDimensionsAssessed: 'Consistency, structure, trust, goal orientation',
    heroHeadline: 'Operations and logistics',
    heroIntroCopy: "Assess high volumes of candidates for operations and logistics roles, to identify the precise, process-led talent that will keep your organisation running smoothly.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in an operations or logistics role which are often hard to spot, such as reliability, attention to detail and accuracy.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including consistency, structure, trust and goal orientation, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-apprentices',
    _type: 'jobCategory',
    name: 'Apprentices',
    slug: { _type: 'slug', current: 'apprentices' },
    keyDimensionsAssessed: 'Collaboration, innovation, structure, trust',
    heroHeadline: 'Apprentices',
    heroIntroCopy: "Rapidly assess high volumes of candidates for apprentice roles, and identify the right talent to develop in your organisation.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in a range of apprentice roles, from project management to engineering, when volumes are high and CVs offer little insight into ability.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including collaboration, innovation, structure and trust, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-claims-and-collections',
    _type: 'jobCategory',
    name: 'Claims and Collections',
    slug: { _type: 'slug', current: 'claims-and-collections' },
    keyDimensionsAssessed: 'Customer excellence, stability, trust, consistency',
    heroHeadline: 'Claims and collections',
    heroIntroCopy: "Assess high volumes of candidates for claims and collections roles, to identify talent with the character your organisation needs to provide the highest standards of service.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in a claims or collections role, including sound judgement, emotional intelligence and the ability to maintain integrity under pressure.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including customer excellence, stability, trust and consistency, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-field-service-and-technicians',
    _type: 'jobCategory',
    name: 'Field Service and Technicians',
    slug: { _type: 'slug', current: 'field-service-and-technicians' },
    keyDimensionsAssessed: 'Customer excellence, structure, trust, consistency',
    heroHeadline: 'Field service and technicians',
    heroIntroCopy: "Assess high volumes of candidates for field service and technician roles, to identify people with the right combination of skills to thrive in your organisation.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in a field service or technician role, ensuring your next hire has the right mix of practical and customer-facing abilities.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including customer excellence, structure, trust and consistency, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-graduates',
    _type: 'jobCategory',
    name: 'Graduates',
    slug: { _type: 'slug', current: 'graduates' },
    keyDimensionsAssessed: 'Customer excellence, competitive drive, trust, structure',
    heroHeadline: 'Graduates',
    heroIntroCopy: "Rapidly assess high volumes of candidates for graduate roles, and identify early careers talent that can become the future of your organisation.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in a graduate role across several sectors, enabling you to differentiate between multiple candidates with similar qualifications.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including customer excellence, competitive drive, trust and structure, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-health-and-social-care',
    _type: 'jobCategory',
    name: 'Health and Social Care',
    slug: { _type: 'slug', current: 'health-and-social-care' },
    keyDimensionsAssessed: 'Nurturing, trust, consistency, stability',
    heroHeadline: 'Health and social care',
    heroIntroCopy: "Assess high volumes of candidates for health and social care roles, to identify the compassionate talent your organisation needs to deliver high quality services.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in a health or social care role, enabling you to strengthen your workforce with resilient, reliable and empathetic staff.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including nurturing, trust, consistency and stability, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-interns',
    _type: 'jobCategory',
    name: 'Interns',
    slug: { _type: 'slug', current: 'interns' },
    keyDimensionsAssessed: 'Innovation, trust, consistency, structure',
    heroHeadline: 'Interns',
    heroIntroCopy: "Quickly assess high volumes of candidates for intern roles, and identify people with the potential to become part of your organisation's talent pipeline.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in an intern role, enabling you to pick candidates out from the crowd who have the ability to develop with your organisation.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including innovation, trust, consistency and structure, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-retail-and-hospitality',
    _type: 'jobCategory',
    name: 'Retail and Hospitality',
    slug: { _type: 'slug', current: 'retail-and-hospitality' },
    keyDimensionsAssessed: 'Customer excellence, stability, consistency, trust',
    heroHeadline: 'Retail and hospitality',
    heroIntroCopy: "Assess high volumes of candidates for retail and hospitality roles, to identify people with the right blend of service-led skills to be an asset to your organisation.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in a retail or hospitality role, so that you can build a frontline workforce of people-friendly problem solvers.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including customer excellence, stability, consistency and trust, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
  {
    _id: 'jobCategory-sales',
    _type: 'jobCategory',
    name: 'Sales',
    slug: { _type: 'slug', current: 'sales' },
    keyDimensionsAssessed: 'Customer excellence, goal-orientation, competitive drive, structure',
    heroHeadline: 'Sales',
    heroIntroCopy: "Assess high volumes of candidates for sales roles, and identify the persistent, commercially-minded talent that will drive revenue growth for your organisation.",
    dimensionsSectionHeading: 'Testing the core dimensions of each role',
    dimensionsSectionBody: 'Our assessments are built around Vero dimensions. These are made up of values, traits and strengths. A total of 16 dimensions combine a range of characteristics that candidates can be assessed on, with each weighted differently to find the ideal profile for your role.',
    inActionSectionHeading: 'Vero Assess in action',
    inActionSectionSubheading: 'Take candidates from application through to interview with a seamless experience that pinpoints performance potential.',
    assessmentsBlockHeading: 'Skills-based assessments at speed',
    assessmentsBlockBody: 'Vero Assess offers ready-to-run online assessments that test the key traits required to be successful in a sales role, including resilience and the ability to perform under pressure without letting standards slip.',
    portalBlockHeading: 'Easy-to-use assessors portal',
    portalBlockBody: "Candidates are measured against a number of dimensions including customer excellence, goal-orientation, competitive drive and structure, with assessors able to see an at-a-glance best-fit score or click through to detailed profiles for deeper candidate analysis. You'll quickly have a verified shortlist of candidates ready to move to the next stage.",
    interviewBlockHeading: 'Consistent, objective interview frameworks',
    interviewBlockBody: "You're provided with interview frameworks and a scoring scale to use for each specific role so you can fairly assess the strengths and weaknesses of candidates at interview. This includes questions, follow up prompts and an evidence-based scorecard, equipping you to make the right hiring decisions.",
    stat1Heading: 'Quick', stat1Body: 'Go live as fast as 48 hours after purchase',
    stat2Heading: 'Cost effective', stat2Body: 'Up to X times cheaper than traditional hiring',
    stat3Heading: 'High volume', stat3Body: 'Process unlimited applicant volumes',
    roleRosterHeading: 'Role roster', roleRosterSubheading: 'Choose your roles.',
    bespokeSectionHeading: 'Looking for something more bespoke?',
    bespokeSectionBody: 'We can also build tailored assessments for hiring, development or training, and end-to-end solutions that take candidates from initial application through to onboarding and beyond.',
    bespokeCTALabel: "Interested? Let's talk",
  },
]

const categoryIdMap: Record<string, string> = {
  'Administration': 'jobCategory-administration',
  'Operations and Logistics': 'jobCategory-operations-and-logistics',
  'Apprentices': 'jobCategory-apprentices',
  'Claims and Collections': 'jobCategory-claims-and-collections',
  'Field Service and Technicians': 'jobCategory-field-service-and-technicians',
  'Graduates': 'jobCategory-graduates',
  'Health and Social Care': 'jobCategory-health-and-social-care',
  'Interns': 'jobCategory-interns',
  'Retail and Hospitality': 'jobCategory-retail-and-hospitality',
  'Sales': 'jobCategory-sales',
}

const rolesData = [
  { name: 'Administrative Assistant', slug: 'administrative-assistant', category: 'Administration', tasks: 'Handles general administrative tasks and office support', strengths: 'Organisation, attention to detail, clear communication' },
  { name: 'Receptionist / Front Desk Coordinator', slug: 'receptionist-front-desk-coordinator', category: 'Administration', tasks: 'Manages front-desk operations and welcomes visitors', strengths: 'Professionalism, communication, friendly and organised' },
  { name: 'Office Coordinator', slug: 'office-coordinator', category: 'Administration', tasks: 'Keeps office operations running smoothly', strengths: 'Organisation, multitasking, strong people skills' },
  { name: 'Scheduling / Appointments Administrator', slug: 'scheduling-appointments-administrator', category: 'Administration', tasks: 'Oversees bookings and appointment arrangements', strengths: 'Organisation, attention to detail, clear communication' },
  { name: 'Document Control / Compliance Administrator', slug: 'document-control-compliance-administrator', category: 'Administration', tasks: 'Maintains accurate records and compliance documentation', strengths: 'Attention to detail, organisation, adherence to procedures' },
  { name: 'Warehouse Operative / Picker-Packer', slug: 'warehouse-operative-picker-packer', category: 'Operations and Logistics', tasks: 'Picks, packs and dispatches goods with accuracy', strengths: 'Attention to detail, efficiency, ability to work at pace' },
  { name: 'Forklift Truck Driver', slug: 'forklift-truck-driver', category: 'Operations and Logistics', tasks: 'Moves goods safely using forklift equipment', strengths: 'Spatial awareness, safety focus, precision in handling materials' },
  { name: 'Transport Planner / Dispatcher', slug: 'transport-planner-dispatcher', category: 'Operations and Logistics', tasks: 'Plans delivery routes and manages transport schedules', strengths: 'Organisation, problem-solving, ability to adapt quickly' },
  { name: 'Warehouse Team Leader / Shift Supervisor', slug: 'warehouse-team-leader-shift-supervisor', category: 'Operations and Logistics', tasks: 'Oversees warehouse operations and team performance', strengths: 'Leadership, organisation, ability to manage productivity targets' },
  { name: 'Inventory Controller / Stock Control Analyst', slug: 'inventory-controller-stock-control-analyst', category: 'Operations and Logistics', tasks: 'Monitors stock levels and maintains inventory accuracy', strengths: 'Analytical ability, attention to detail, strong systems and reporting skills' },
  { name: 'Engineering / Maintenance Degree Apprentice', slug: 'engineering-maintenance-degree-apprentice', category: 'Apprentices', tasks: 'Maintains and improves equipment performance', strengths: 'Technical aptitude, problem-solving, strong safety and reliability focus' },
  { name: 'IT Support / Digital Support Degree Apprentice', slug: 'it-support-digital-support-degree-apprentice', category: 'Apprentices', tasks: 'Resolves IT issues and provides technical assistance', strengths: 'Troubleshooting skills, patience, clear communication with non-technical users' },
  { name: 'Chartered Manager Degree Apprentice', slug: 'chartered-manager-degree-apprentice', category: 'Apprentices', tasks: 'Develops leadership capability while managing teams and projects', strengths: 'Decision-making, accountability, strong interpersonal effectiveness' },
  { name: 'Project Management Degree Apprentice', slug: 'project-management-degree-apprentice', category: 'Apprentices', tasks: 'Contributes to project delivery from planning through to completion', strengths: 'Organisation, time management, ability to coordinate multiple stakeholders' },
  { name: 'Data Analyst / Digital Solutions Degree Apprentice', slug: 'data-analyst-digital-solutions-degree-apprentice', category: 'Apprentices', tasks: 'Analyses data to inform decisions and develop digital solutions', strengths: 'Analytical thinking, attention to detail, proficiency with digital tools' },
  { name: 'Claims Handler', slug: 'claims-handler', category: 'Claims and Collections', tasks: 'Manages insurance claims from first contact through to resolution', strengths: 'Attention to detail, communication, sound judgement' },
  { name: 'First Notification of Loss Agent', slug: 'first-notification-of-loss-agent', category: 'Claims and Collections', tasks: 'Takes initial loss reports and gathers accurate information', strengths: 'Empathy, active listening, clear information capture' },
  { name: 'Claims Investigator / Fraud Screening Analyst', slug: 'claims-investigator-fraud-screening-analyst', category: 'Claims and Collections', tasks: 'Reviews claims for accuracy and investigates potential fraud', strengths: 'Analytical thinking, attention to detail, critical judgement' },
  { name: 'Collections Agent', slug: 'collections-agent', category: 'Claims and Collections', tasks: 'Contacts customers to recover outstanding payments', strengths: 'Negotiation, resilience, ability to handle difficult conversations' },
  { name: 'Credit Controller / Collections Team Leader', slug: 'credit-controller-collections-team-leader', category: 'Claims and Collections', tasks: 'Oversees credit control activity and leads collections teams', strengths: 'Leadership, financial awareness, strong decision-making and communication' },
  { name: 'Field Service Engineer', slug: 'field-service-engineer', category: 'Field Service and Technicians', tasks: 'Diagnoses and resolves equipment faults on-site', strengths: 'Technical expertise, problem-solving, customer interaction' },
  { name: 'Installation Technician', slug: 'installation-technician', category: 'Field Service and Technicians', tasks: 'Installs equipment and systems at customer sites', strengths: 'Technical accuracy, attention to detail, communication' },
  { name: 'Maintenance Technician (PPM)', slug: 'maintenance-technician-ppm', category: 'Field Service and Technicians', tasks: 'Carries out planned preventative maintenance across sites', strengths: 'Technical knowledge, reliability, proactive fault prevention' },
  { name: 'Service Coordinator / Field Scheduler', slug: 'service-coordinator-field-scheduler', category: 'Field Service and Technicians', tasks: 'Coordinates field engineer schedules and customer appointments', strengths: 'Organisation, communication, priority management' },
  { name: 'Mobile Repair Technician', slug: 'mobile-repair-technician', category: 'Field Service and Technicians', tasks: 'Repairs equipment and devices at customer locations', strengths: 'Diagnostic ability, adaptability, quality workmanship' },
  { name: 'Graduate Customer Success / Support', slug: 'graduate-customer-success-support', category: 'Graduates', tasks: 'Supports customers to get maximum value from products or services', strengths: 'Empathy, communication, proactive problem-solving' },
  { name: 'Graduate Operations / Business Operations', slug: 'graduate-operations-business-operations', category: 'Graduates', tasks: 'Supports operational efficiency and cross-functional coordination', strengths: 'Analytical thinking, organisation, cross-functional coordination' },
  { name: 'Graduate Finance', slug: 'graduate-finance', category: 'Graduates', tasks: 'Supports financial reporting, analysis and compliance', strengths: 'Numerical ability, attention to detail, commercial awareness' },
  { name: 'Graduate HR / People', slug: 'graduate-hr-people', category: 'Graduates', tasks: 'Supports HR processes and people-related initiatives', strengths: 'Interpersonal skills, confidentiality, organisational ability' },
  { name: 'Graduate Sales / Commercial', slug: 'graduate-sales-commercial', category: 'Graduates', tasks: 'Develops new business and supports commercial growth', strengths: 'Resilience, persuasion, results-driven mindset' },
  { name: 'Care Assistant', slug: 'care-assistant', category: 'Health and Social Care', tasks: 'Provides personal care and support to individuals in care settings', strengths: 'Compassion, patience, people skills' },
  { name: 'Support Worker', slug: 'support-worker', category: 'Health and Social Care', tasks: 'Assists individuals with daily living and wellbeing', strengths: 'Empathy, resilience, trust building' },
  { name: 'Home Care Worker / Domiciliary Carer', slug: 'home-care-worker-domiciliary-carer', category: 'Health and Social Care', tasks: 'Delivers care and support to clients in their own homes', strengths: 'Reliability, compassion, works independently' },
  { name: 'Senior Care Assistant / Team Leader', slug: 'senior-care-assistant-team-leader', category: 'Health and Social Care', tasks: 'Leads a team of care assistants and ensures quality of care', strengths: 'Leadership, empathy, organisation, decision making' },
  { name: 'Care Coordinator / Scheduler (Home Care)', slug: 'care-coordinator-scheduler-home-care', category: 'Health and Social Care', tasks: 'Plans and coordinates care schedules for home care clients', strengths: 'Organisation, communication, managing changing priorities' },
  { name: 'Business Operations / Operations Intern', slug: 'business-operations-operations-intern', category: 'Interns', tasks: 'Supports operational teams with day-to-day tasks and projects', strengths: 'Adaptability, organisation, willingness to learn' },
  { name: 'Sales / Commercial Intern', slug: 'sales-commercial-intern', category: 'Interns', tasks: 'Assists the sales team with prospecting and commercial activity', strengths: 'Communication, curiosity, proactive and target-focused' },
  { name: 'Marketing Intern', slug: 'marketing-intern', category: 'Interns', tasks: 'Supports marketing campaigns and content creation', strengths: 'Creativity, attention to detail, digital awareness' },
  { name: 'Finance Intern', slug: 'finance-intern', category: 'Interns', tasks: 'Assists with financial data entry, reporting and analysis', strengths: 'Numerical accuracy, organisation, eagerness to learn' },
  { name: 'People / HR Intern', slug: 'people-hr-intern', category: 'Interns', tasks: 'Supports HR team with recruitment, onboarding and admin', strengths: 'Confidentiality, organisation, strong people skills' },
  { name: 'Retail Sales Assistant / Sales Associate', slug: 'retail-sales-assistant-sales-associate', category: 'Retail and Hospitality', tasks: 'Serves customers and supports the retail sales floor', strengths: 'Customer service, product knowledge, approachable' },
  { name: 'Retail Supervisor / Shift Leader', slug: 'retail-supervisor-shift-leader', category: 'Retail and Hospitality', tasks: 'Leads retail floor operations and supervises team members', strengths: 'Leadership, organisation, ability to motivate teams' },
  { name: 'Hospitality Front of House Team Member', slug: 'hospitality-front-of-house-team-member', category: 'Retail and Hospitality', tasks: 'Delivers front-of-house service in hospitality environments', strengths: 'Communication, attentiveness, customer-focused' },
  { name: 'Barista', slug: 'barista', category: 'Retail and Hospitality', tasks: 'Prepares and serves coffee and beverages to customers', strengths: 'Attention to detail, works quickly, strong customer service' },
  { name: 'Kitchen Team Member / Kitchen Porter', slug: 'kitchen-team-member-kitchen-porter', category: 'Retail and Hospitality', tasks: 'Supports kitchen operations and maintains cleanliness', strengths: 'Reliability, teamwork, works under pressure' },
  { name: 'Sales Development Representative – High Volume', slug: 'sales-development-representative-high-volume', category: 'Sales', tasks: 'Makes high volumes of outbound calls to generate pipeline', strengths: 'Resilience, energy, ability to handle rejection' },
  { name: 'Sales Development Representative – Enterprise', slug: 'sales-development-representative-enterprise', category: 'Sales', tasks: 'Targets enterprise accounts with strategic outbound outreach', strengths: 'Research ability, strategic thinking, professional communication' },
  { name: 'Inside Sales Representative', slug: 'inside-sales-representative', category: 'Sales', tasks: 'Manages inbound leads and drives revenue through phone and digital channels', strengths: 'Persuasion, product knowledge, consistent target focus' },
  { name: 'Account Executive', slug: 'account-executive', category: 'Sales', tasks: 'Closes new business and manages the sales cycle end-to-end', strengths: 'Negotiation, commercial acumen, results-driven' },
  { name: 'Account Manager', slug: 'account-manager', category: 'Sales', tasks: 'Manages existing client relationships and drives retention and growth', strengths: 'Relationship-building, responsiveness, customer satisfaction' },
]

const roles = rolesData.map((r) => ({
  _id: `role-${r.slug}`,
  _type: 'role',
  name: r.name,
  slug: { _type: 'slug', current: r.slug },
  parentCategory: { _type: 'reference', _ref: categoryIdMap[r.category] },
  tasks: r.tasks,
  strengths: r.strengths,
}))

const homePageDoc = {
  _id: 'homePage',
  _type: 'homePage',
  heroTitle: 'Identify authentic talent. Make strategic hiring decisions.',
  heroIntro:
    'Evaluate applicants in depth and at speed. Vero Assess reduces workloads, enhances recruitment and delivers the talent your organisation needs.',
  heroCTALabel: 'Get started',
  howItWorksHeading: 'Getting started is straightforward',
  howItWorksIntro:
    'Getting started with Vero Assess is straightforward. Here\u2019s what to expect.',
  steps: [
    {
      _key: 'step1',
      title: 'Choose your roles',
      body: 'Browse 10 job families and select the roles you\u2019re hiring for. Each comes with a ready-to-go package of science-backed assessments, built around the specific traits, values and strengths that matter for that role. No configuration required.',
      ctaLabel: 'Browse job families',
      ctaHref: '/assessments',
    },
    {
      _key: 'step2',
      title: 'Assess your candidates',
      body: 'Send assessments directly to candidates and let Vero Assess do the work. Candidates complete their assessments online, at their own pace, through a dedicated portal built for accessibility and ease of use. You can go live within 48 hours of purchase.',
      ctaLabel: 'See how it works',
      ctaHref: '/how-it-works',
    },
    {
      _key: 'step3',
      title: 'Make the right hire',
      body: 'Review results in your assessor dashboard. Each candidate gets a percentage best-fit score alongside detailed performance data across every dimension. Pair that with the role-specific interview frameworks provided, and you have everything you need to make a confident, objective hiring decision.',
      ctaLabel: 'Get started',
      ctaHref: '/get-started',
    },
  ],
}

async function seed() {
  console.log('🌱 Starting Sanity seed...\n')
  const allDocs = [homePageDoc, ...pricingTiers, ...jobCategories, ...roles]
  let success = 0
  let failed = 0
  for (const doc of allDocs) {
    try {
      await client.createOrReplace(doc)
      const label = (doc as Record<string, unknown>).name ?? doc._id
      console.log(`  ✓ ${doc._type}: ${label}`)
      success++
    } catch (err) {
      const label = (doc as Record<string, unknown>).name ?? doc._id
      console.error(`  ✗ Failed: ${label}`, err)
      failed++
    }
  }
  console.log(`\n✅ Seed complete — ${success} documents written, ${failed} failed.`)
}

seed().catch((err) => { console.error('Seed failed:', err); process.exit(1) })
